default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: my_api_development
  username: <%= ENV.fetch("DATABASE_USER", "myapp") %>
  password: <%= ENV.fetch("MY_API_DEVELOPMENT_PASSWORD", "avongs") %>
  host: localhost

test:
  <<: *default
  database: my_api_test
  username: <%= ENV.fetch("DATABASE_USER", "myapp") %>
  password: <%= ENV.fetch("MY_API_TEST_PASSWORD", "avongs") %>
  host: localhost

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "my_api_db_ovap") %>
  username: <%= ENV.fetch("DATABASE_USER", "my_api_db_ovap_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "0L6HoUbe5YNy06gIsyRq3KHkw2aixwmp") %>
  host: <%= ENV.fetch("DATABASE_HOST", "dpg-cv05tpq3esus73e5e4t0-a.oregon-postgres.render.com") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  pool: 5

cable:
  <<: *default
  database: <%= ENV.fetch("CABLE_DATABASE_NAME", "#{ENV["DATABASE_NAME"]}_cable") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

queue:
  <<: *default
  database: <%= ENV.fetch("QUEUE_DATABASE_NAME", "#{ENV["DATABASE_NAME"]}_queue") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

cache:
  <<: *default
  database: <%= ENV.fetch("CACHE_DATABASE_NAME", "#{ENV["DATABASE_NAME"]}_cache") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
