default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME', 'default_user') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'default_pass') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  database: my_api_development

test:
  <<: *default
  database: my_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 10




  # cache:
  #   <<: *default
  #   database: my_api_cache_production
  #   username: <%= ENV.fetch('CACHE_DB_USERNAME', 'my_api_user') %>
  #   password: <%= ENV.fetch('CACHE_DB_PASSWORD', 'my_api_password') %>
  #   host: <%= ENV.fetch('CACHE_DB_HOST', 'localhost') %>
